-- CreateTable
CREATE TABLE `USER` (
    `USER_NO` INTEGER NOT NULL AUTO_INCREMENT,
    `USER_UUID` VARCHAR(191) NOT NULL,
    `USER_EMAIL` VARCHAR(191) NOT NULL,
    `USER_NAME` VARCHAR(191) NOT NULL,
    `USER_PROFILE_PHOTO` VARCHAR(191) NOT NULL,
    `USER_REGISTERED_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `USER_LAST_LOGIN_DATE` DATETIME(3) NOT NULL,
    `USER_STATE` ENUM('DORMANT', 'ACTIVE', 'SUSPENDED') NOT NULL DEFAULT 'ACTIVE',
    `USER_EMAIL_VERIFIED` BOOLEAN NOT NULL DEFAULT false,

    UNIQUE INDEX `USER_USER_UUID_key`(`USER_UUID`),
    UNIQUE INDEX `USER_USER_EMAIL_key`(`USER_EMAIL`),
    PRIMARY KEY (`USER_NO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `USER_OAUTH` (
    `USER_NO` INTEGER NOT NULL,
    `USER_OAUTH_PROVIDER` VARCHAR(191) NOT NULL,
    `USER_OAUTH_ID` VARCHAR(191) NOT NULL,

    INDEX `USER_OAUTH_USER_NO_idx`(`USER_NO`),
    INDEX `USER_OAUTH_USER_OAUTH_ID_USER_OAUTH_PROVIDER_idx`(`USER_OAUTH_ID`, `USER_OAUTH_PROVIDER`),
    UNIQUE INDEX `USER_OAUTH_USER_OAUTH_ID_USER_OAUTH_PROVIDER_key`(`USER_OAUTH_ID`, `USER_OAUTH_PROVIDER`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `USER_SOCIAL` (
    `USER_SOCIAL_TYPE` VARCHAR(191) NOT NULL,
    `USER_NO` INTEGER NOT NULL,
    `USER_SOCIAL_CONTENT` VARCHAR(191) NOT NULL,

    INDEX `USER_SOCIAL_USER_NO_USER_SOCIAL_TYPE_idx`(`USER_NO`, `USER_SOCIAL_TYPE`),
    UNIQUE INDEX `USER_SOCIAL_USER_SOCIAL_TYPE_USER_NO_key`(`USER_SOCIAL_TYPE`, `USER_NO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PROBLEM` (
    `PROBLEM_NO` INTEGER NOT NULL AUTO_INCREMENT,
    `PROBLEM_UUID` VARCHAR(191) NOT NULL,
    `PROBLEM_SOURCE` VARCHAR(191) NOT NULL,
    `PROBLEM_SOURCE_ID` VARCHAR(191) NOT NULL,
    `PROBLEM_SOURCE_URL` VARCHAR(191) NOT NULL,
    `PROBLEM_TITLE` VARCHAR(191) NOT NULL,
    `PROBLEM_LEVEL` INTEGER NOT NULL,
    `PROBLEM_LEVEL_TEXT` VARCHAR(191) NOT NULL,
    `PROBLEM_REGISTERED_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `PROBLEM_UPDATED_DATE` DATETIME(3) NOT NULL,
    `PROBLEM_INPUT` VARCHAR(600) NOT NULL,
    `PROBLEM_OUTPUT` VARCHAR(600) NOT NULL,
    `PROBLEM_HINT` VARCHAR(600) NOT NULL DEFAULT '',
    `PROBLEM_LIMIT` VARCHAR(191) NOT NULL,
    `PROBLEM_ANSWER_COUNT` INTEGER NOT NULL,
    `PROBLEM_ANSWER_PEOPLE_COUNT` INTEGER NOT NULL,
    `PROBLEM_SUBMIT_COUNT` INTEGER NOT NULL,
    `PROBLEM_TIMEOUT` INTEGER NOT NULL,
    `PROBLEM_MEMORY_LIMIT` INTEGER NOT NULL,

    UNIQUE INDEX `PROBLEM_PROBLEM_UUID_key`(`PROBLEM_UUID`),
    UNIQUE INDEX `PROBLEM_PROBLEM_SOURCE_PROBLEM_SOURCE_ID_key`(`PROBLEM_SOURCE`, `PROBLEM_SOURCE_ID`),
    PRIMARY KEY (`PROBLEM_NO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PROBLEM_CONTENT` (
    `PROBLEM_CONTENT` VARCHAR(1000) NOT NULL,
    `PROBLEM_CONTENT_TYPE` VARCHAR(191) NOT NULL,
    `PROBLEM_CONTENT_ORDER` INTEGER NOT NULL,
    `PROBLEM_NO` INTEGER NOT NULL,

    INDEX `PROBLEM_CONTENT_PROBLEM_NO_PROBLEM_CONTENT_ORDER_idx`(`PROBLEM_NO`, `PROBLEM_CONTENT_ORDER`),
    UNIQUE INDEX `PROBLEM_CONTENT_PROBLEM_NO_PROBLEM_CONTENT_ORDER_key`(`PROBLEM_NO`, `PROBLEM_CONTENT_ORDER`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PROBLEM_TYPE` (
    `PROBLEM_TYPE_NAME` VARCHAR(191) NOT NULL,
    `PROBLEM_NO` INTEGER NOT NULL,

    INDEX `PROBLEM_TYPE_PROBLEM_NO_PROBLEM_TYPE_NAME_idx`(`PROBLEM_NO`, `PROBLEM_TYPE_NAME`),
    UNIQUE INDEX `PROBLEM_TYPE_PROBLEM_NO_PROBLEM_TYPE_NAME_key`(`PROBLEM_NO`, `PROBLEM_TYPE_NAME`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PROBLEM_INPUT_OUTPUT` (
    `PROBLEM_INPUT_OUTPUT_ORDER` INTEGER NOT NULL,
    `PROBLEM_INPUT` VARCHAR(600) NOT NULL,
    `PROBLEM_OUTPUT` VARCHAR(600) NOT NULL,
    `PROBLEM_NO` INTEGER NOT NULL,

    INDEX `PROBLEM_INPUT_OUTPUT_PROBLEM_NO_idx`(`PROBLEM_NO`),
    UNIQUE INDEX `PROBLEM_INPUT_OUTPUT_PROBLEM_NO_PROBLEM_INPUT_OUTPUT_ORDER_key`(`PROBLEM_NO`, `PROBLEM_INPUT_OUTPUT_ORDER`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `USER_PROBLEM_STATE` (
    `userNo` INTEGER NOT NULL,
    `problemNo` INTEGER NOT NULL,
    `state` INTEGER NOT NULL,

    UNIQUE INDEX `USER_PROBLEM_STATE_userNo_problemNo_key`(`userNo`, `problemNo`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `USER_OAUTH` ADD CONSTRAINT `USER_OAUTH_USER_NO_fkey` FOREIGN KEY (`USER_NO`) REFERENCES `USER`(`USER_NO`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `USER_SOCIAL` ADD CONSTRAINT `USER_SOCIAL_USER_NO_fkey` FOREIGN KEY (`USER_NO`) REFERENCES `USER`(`USER_NO`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PROBLEM_CONTENT` ADD CONSTRAINT `PROBLEM_CONTENT_PROBLEM_NO_fkey` FOREIGN KEY (`PROBLEM_NO`) REFERENCES `PROBLEM`(`PROBLEM_NO`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PROBLEM_TYPE` ADD CONSTRAINT `PROBLEM_TYPE_PROBLEM_NO_fkey` FOREIGN KEY (`PROBLEM_NO`) REFERENCES `PROBLEM`(`PROBLEM_NO`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PROBLEM_INPUT_OUTPUT` ADD CONSTRAINT `PROBLEM_INPUT_OUTPUT_PROBLEM_NO_fkey` FOREIGN KEY (`PROBLEM_NO`) REFERENCES `PROBLEM`(`PROBLEM_NO`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `USER_PROBLEM_STATE` ADD CONSTRAINT `USER_PROBLEM_STATE_userNo_fkey` FOREIGN KEY (`userNo`) REFERENCES `USER`(`USER_NO`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `USER_PROBLEM_STATE` ADD CONSTRAINT `USER_PROBLEM_STATE_problemNo_fkey` FOREIGN KEY (`problemNo`) REFERENCES `PROBLEM`(`PROBLEM_NO`) ON DELETE RESTRICT ON UPDATE CASCADE;
