name: Deploy to Jenkins

on:
  push:
    branches:
      - dev/algogo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Jenkins job
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}  # Jenkins URL
          ALGOGO_DEPLOY_TOKEN: ${{ secrets.ALGOGO_DEPLOY_TOKEN }}  # Jenkins Token
        run: |
          curl -X POST "${{ env.JENKINS_URL }}/job/algogo_main/buildWithParameters?token=${{ env.ALGOGO_DEPLOY_TOKEN }}"